[성종호][modify]product_detail_view
wecode-bootcamp-korea/27-1st-Brokurly-backend pull request #6
Opened 2021-12-03 07:09 UTC by SeongJongHo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-12-05 15:06 UTC, jamessoun93 requested changes

2021-12-05 15:06 UTC, jamessoun93 commented on orders/views.py
> +        return JsonResponse({},status=200)
상품상세정보를 GET 하는 기능을 담은 PR에 관련없는 수정사항들이 있네요.
기능상으로 문제가 되는것은 아니기 때문에 이번에는 딱히 없애거나 하실 필요까지는 없지만 다음부터는 꼭 확인해주세요!

2021-12-05 15:06 UTC, jamessoun93 commented on products/urls.py
> +  path("/<int:product_id>",ProductDetailView.as_view())
들여쓰기 네 칸으로 통일해주세요.
```suggestion
    path("/<int:product_id>",ProductDetailView.as_view())
```

2021-12-05 15:06 UTC, jamessoun93 commented on products/views.py
> +            return JsonResponse({"message" : "INVALID_PRODUCT"}, status = 401)
HTTP Status Code 401 은 UNAUTHORIZED 라는 의미의 코드입니다.
`401` 이 해당 exception 처럼 원하는 리소스가 존재하지 않을때 쓰는 HTTP Status Code 일까요?
수정해주세요!

2021-12-05 15:06 UTC, jamessoun93 commented on products/views.py
> +              "images"       : [image.url for image in product.image_set.all()]
들여쓰기 네 칸으로 통일해주세요!

2021-12-05 15:06 UTC, jamessoun93 commented on products/views.py
> +            product = Product.objects.get(id=product_id)
`get()` 메소드에서 발생할 수 있는 exception 처리 아래에서 잘 해주셨는데 여기서 잡아주셔야할 exception 은 하나가 더 있습니다. 찾아서 추가해주세요!

2021-12-05 15:13 UTC, jamessoun93 commented
추가로, PR template 에 해당 기능에 대한 설명 상세하게 기록해주시고 통신결과 스샷 첨부해주세요.

2021-12-06 09:52 UTC, lordmyshepherd commented
LGTM 👍🏻

2021-12-06 09:53 UTC, merged