[Add] core - validator.py 추가
wecode-bootcamp-korea/27-1st-Brokurly-backend pull request #8
Opened 2021-12-03 10:11 UTC by Ted0527

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- ValidationError 를 모듈화하여 다른 곳에서 import 하여 사용할 목적

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입, 로그인 입력 데이터 유효성 검사
- 이메일, 패스워드 유효성 검사 및 유저아이디 중복 검사 포함

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 다양한 validation error 상황을 고려하여 각각의 함수로 세분화 하는 부분이 헷갈리면서도 이렇게 까지 세분화 해야할까 하는 의문도 생겼습니다.

<br />

## :: 기타 질문 및 특이 사항
-

2021-12-05 15:12 UTC, jamessoun93 requested changes
migration 파일들이 수정된 내역이 함께 올라왔는데, 이렇게 되면 머지했을때 팀원들 PR 에 충돌이 발생하게됩니다. migration 파일들을 지우고 새로 migration 작업을 거치신 것 같은데 팀원들도 다 알고 있는 변경사항인지 컨펌해주세요.

2021-12-05 15:12 UTC, jamessoun93 commented on .gitignore
> +products.csv
이렇게되면 csv 파일이 생길때마다 항상 `.gitignore` 파일을 수정해줘야하는 불편함이 있습니다.
아래처럼 작성하면 모든 csv 확장자를 가진 파일을 gitignore 해줄 수 있습니다.
```
*.csv
```

2021-12-05 15:12 UTC, jamessoun93 commented on core/validator.py
> +        )
```suggestion
        raise ValidationError('Invalid Email')
```

2021-12-05 15:12 UTC, jamessoun93 commented on core/validator.py
> +        )
```suggestion
        raise ValidationError('Duplicated Email Exists')
```

2021-12-05 15:12 UTC, jamessoun93 commented on core/validator.py
> +        )
```suggestion
        raise ValidationError('Invalid Password')
```

2021-12-05 15:12 UTC, jamessoun93 commented on core/validator.py
> +        )
```suggestion
        raise ValidationError('Invalid Username')
```

2021-12-05 15:12 UTC, jamessoun93 commented on core/validator.py
> +        )
```suggestion
        raise ValidationError('Duplicated Username Exists')
```

2021-12-05 15:12 UTC, jamessoun93 commented on core/validator.py
> +        )
```suggestion
        raise ValidationError('Invalid Contact')
```

2021-12-06 06:25 UTC, Ted0527 commented on .gitignore
> +products.csv
말씀주신 migration 관련 팀원들과 확인했습니다. main에 push 할 당시 migration 한 상태로 push 했었고,
그것을 pull main 한 후에 feature/validator branch 를 생성하여 작업했기에, 문제 없을 것으로 판단됩니다.

2021-12-06 07:45 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-06 07:45 UTC, merged